"""Add aprovado e adiantamento_decimo

Revision ID: ba43a1bcf15f
Revises: c3672c4c3dc8
Create Date: 2025-10-23 17:19:36.757678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba43a1bcf15f'
down_revision = 'c3672c4c3dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ferias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adiantamento_decimo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('aprovado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ferias', schema=None) as batch_op:
        batch_op.drop_column('aprovado')
        batch_op.drop_column('adiantamento_decimo')

    # ### end Alembic commands ###
