"""Novo campo Marcacoes, novas mudanças no db

Revision ID: 0ae74cfcc0bb
Revises: 
Create Date: 2025-09-10 16:12:59.558998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ae74cfcc0bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pontos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marcacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('ponto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ponto_id'], ['pontos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ponto')
    op.drop_table('log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('acao', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('data_hora', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('log_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('log_pkey'))
    )
    op.create_table('ponto',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('hora_entrada', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('hora_saida', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('horas_trabalhadas', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], name=op.f('ponto_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ponto_pkey'))
    )
    op.drop_table('marcacoes')
    op.drop_table('pontos')
    # ### end Alembic commands ###
