"""adicionados campos cidade e uf

Revision ID: 0c64eb084cd6
Revises: 0ae74cfcc0bb
Create Date: 2025-09-10 16:59:04.093866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c64eb084cd6'
down_revision = '0ae74cfcc0bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('uf', sa.String(length=2), nullable=True))
        batch_op.drop_column('cidade_uf')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cidade_uf', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('uf')
        batch_op.drop_column('cidade')

    # ### end Alembic commands ###
